# Generated by Django 2.1.2 on 2018-10-21 20:05

from django.db import migrations, models
import game.models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamesession',
            name='uri',
            field=models.TextField(default=game.models._generate_unique_uri),
        ),
    ]
