# Generated by Django 2.1.2 on 2018-12-28 17:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_won', models.IntegerField(default=0)),
                ('total_score', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='game',
            name='lang',
            field=models.CharField(choices=[('US', 'en_US'), ('PL', 'pl_PL')], default='PL', max_length=2),
        ),
        migrations.AlterField(
            model_name='game',
            name='step',
            field=models.CharField(choices=[('PRE', 'not_started'), ('IDL', 'started_not_answering'), ('ANS', 'started_answering')], default='PRE', max_length=3),
        ),
    ]
