# Generated by Django 2.1.2 on 2018-11-06 11:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game', '0003_gamesessionmessage_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameSessionAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('text', models.TextField(max_length=2000)),
                ('type', models.TextField(default='text', max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GameSessionChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('choice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='game.GameSessionAnswer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GameSessionTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('text', models.TextField(max_length=2000)),
                ('game_session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='game.GameSession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='gamesessionchoice',
            name='game_task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='choices', to='game.GameSessionTask'),
        ),
        migrations.AddField(
            model_name='gamesessionchoice',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gamesessionanswer',
            name='game_task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='answers', to='game.GameSessionTask'),
        ),
        migrations.AddField(
            model_name='gamesessionanswer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
