# Generated by Django 2.1.2 on 2019-01-05 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_auto_20181228_1758'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='step',
            new_name='status',
        ),
    ]
