# Generated by Django 2.1.2 on 2018-11-09 23:25

from django.db import migrations, models
import django.db.models.deletion
import game.models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_auto_20181106_1122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamesessionmessage',
            name='game_session',
        ),
        migrations.RemoveField(
            model_name='gamesessionmessage',
            name='user',
        ),
        migrations.RemoveField(
            model_name='gamesession',
            name='create_date',
        ),
        migrations.RemoveField(
            model_name='gamesession',
            name='step',
        ),
        migrations.RemoveField(
            model_name='gamesession',
            name='update_date',
        ),
        migrations.RemoveField(
            model_name='gamesessionanswer',
            name='create_date',
        ),
        migrations.RemoveField(
            model_name='gamesessionanswer',
            name='update_date',
        ),
        migrations.RemoveField(
            model_name='gamesessionanswer',
            name='user',
        ),
        migrations.RemoveField(
            model_name='gamesessionchoice',
            name='create_date',
        ),
        migrations.RemoveField(
            model_name='gamesessionchoice',
            name='update_date',
        ),
        migrations.RemoveField(
            model_name='gamesessionchoice',
            name='user',
        ),
        migrations.RemoveField(
            model_name='gamesessionplayer',
            name='create_date',
        ),
        migrations.RemoveField(
            model_name='gamesessionplayer',
            name='update_date',
        ),
        migrations.RemoveField(
            model_name='gamesessiontask',
            name='create_date',
        ),
        migrations.RemoveField(
            model_name='gamesessiontask',
            name='update_date',
        ),
        migrations.RemoveField(
            model_name='gamesessiontask',
            name='user',
        ),
        migrations.AddField(
            model_name='gamesession',
            name='lang',
            field=models.CharField(choices=[('EN', 'en_US'), ('PL', 'pl_PL')], default=game.models.Lang('en_US'), max_length=2),
        ),
        migrations.AddField(
            model_name='gamesessionanswer',
            name='player',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='game.GameSessionPlayer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gamesessionchoice',
            name='player',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='game.GameSessionPlayer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gamesessiontask',
            name='done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gamesessiontask',
            name='player',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='game.GameSessionPlayer'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gamesession',
            name='game_type',
            field=models.CharField(choices=[('TRE', 'Trends')], default=game.models.GameType('Trends'), max_length=3),
        ),
        migrations.AlterField(
            model_name='gamesessionanswer',
            name='game_task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='game.GameSessionTask'),
        ),
        migrations.AlterField(
            model_name='gamesessionchoice',
            name='choice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.GameSessionAnswer'),
        ),
        migrations.AlterField(
            model_name='gamesessionchoice',
            name='game_task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='game.GameSessionTask'),
        ),
        migrations.AlterField(
            model_name='gamesessionplayer',
            name='game_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='game.GameSession'),
        ),
        migrations.AlterField(
            model_name='gamesessiontask',
            name='game_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='game.GameSession'),
        ),
        migrations.DeleteModel(
            name='GameSessionMessage',
        ),
    ]
