# Generated by Django 2.1.2 on 2018-11-10 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_auto_20181109_2325'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='started',
            field=models.BooleanField(default=False),
        ),
    ]
