# Generated by Django 2.1.2 on 2018-11-17 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_gamesession_started'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamesessiontask',
            name='player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='game.GameSessionPlayer'),
        ),
    ]
