# Generated by Django 2.1.2 on 2018-11-20 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_auto_20181117_2235'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesessionanswer',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
